# This program says hello and asks for my name.
print('Hello world!')
print('What is your name?')
myName = input()
print('It is good to meet you, ' +myName)
print('What is your age?')
myAge = input()
print('You are, ' +myAge)
print(' Now I will need to ask you two more questions... Okay?')
Yes = input()
print('What is your favorite sport?')
Football = input()
print('Okay...What is Your favorite football team?')
ThePittsburgSteelers = input()
print('Umm...Could be better. Thank You!')